project:
  type: website
  output-dir: docs

website:
  title: "Vincent Yi's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: Education
      - href: contact.qmd
        text: Contact
      - href: about.qmd
        text: About



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



